---
engines:
  duplication:
    enabled: true
    exclude_paths:
      - elide-core/src/test/java/com/paiondata/elide/graphql/*
exclude_paths:
  - elide-core/src/test/java/com/paiondata/elide/graphql/*
